# Configuration file : default --
# Based on config : https://github.com/lorenwest/node-config/wiki/Configuration-Files

server:
  port: 3000
  static: true
  live_reload: true

database:
  host: 'localhost'
  port: 2424
  username: 'root'
  password: 'yourpassword'
  dbname: 'genetracker'

# Override this !
secret_token: 'P3RoJCBuof44T2tZm7O9'

# -- Data Schema --
# Don't touch unless you know what you're doing !


data_schema:
  models:
    - name: Rat
      type: animal
      path: rats
      path_base: animals
      property:
        - name: strain
          type: list
          list:
            - id: long_evans
            - id: wistar
            - id: sprague_dawley
          allow_other: true
          display_datatable: true
        - name: sex
          type: list
          list:
            - id: male
            - id: female
          allow_other: false
          display_datatable: true
        - name: id
          type: text
          display_datatable: true
        - name: date_enter
          type: date
        - name: date_birth
          type: date
        - name: date_exit
          type: date
        - name: date_death
          type: date
        - name: death
          type: list
          list:
            - id: pentobarbital_end_project
            - id: pentobarbital_tissue_sample
            - id: pentobarbital_suffering
            - id: pre_surgery
            - id: per_surgery
            - id: post_surgery
            - id: beheaded_bio_mol
            - id: found_dead
          allow_other: true
          allow_empty: true
        - name: origin
          type: list
          list:
            - id: janvier_labs
            - id: charles_river
          allow_other: true
        - name: addressee
          type: text
        - name: project
          type: reference
          reference_to: Project
          display_datatable: true
          property_to_display: [ id_apafis ]

    - name: Mus
      type: animal
      path: mice
      path_base: animals
      property:
        - name: id
          type: text
          display_datatable: true
        - name: chip
          type: text
          display_datatable: true
        - name: sex
          type: list
          list:
            - id: male
            - id: female
          allow_other: false
          display_datatable: true
        - name: strain
          type: text
          display_datatable: true
        - name: lineage
          type: text
          display_datatable: true
        - name: genotype
          type: text
          display_datatable: true
        - name: date_enter
          type: date
        - name: date_birth
          type: date
        - name: origin
          type: list
          list:
            - id: janvier_labs
            - id: charles_river
            - id: jax_mice
          allow_other: true
        - name: date_exit
          type: date
        - name: date_death
          type: date
        - name: death
          type: list
          list:
            - id: dislocation_end_project
            - id: dislocation_tissue_sample
            - id: dislocation_suffering
            - id: dislocation_unusable
            - id: pentobarbital_end_project
            - id: pentobarbital_tissue_sample
            - id: pentobarbital_suffering
            - id: pre_surgery
            - id: per_surgery
            - id: post_surgery
            - id: beheaded_bio_mol
            - id: found_dead
          allow_other: true
          allow_empty: true
        - name: addressee
          type: text
        - name: project
          type: reference
          reference_to: Project
          property_to_display: [ id_apafis ]

    - name: Project
      type: other
      path: projects
      path_base: others
      property:
        - name: id_apafis
          type: text
          display_datatable: true
        - name: creator
          type: reference
          reference_to: User
          display_datatable: true
          property_to_display: [ first_name, last_name ]

    - name: User
      type: user
      path: users
      path_base:
      property:
        - name: username
          type: text
          display_datatable: true
        - name: password
          type: password
        - name: role
          type: list
          list:
            - id: admin
            - id: project_manager
            - id: viewer
          allow_other: false
          display_datatable: true
        - name: first_name
          type: text
          display_datatable: true
        - name: last_name
          type: text
          display_datatable: true

