# Configuration file : default --
# Based on config : https://github.com/lorenwest/node-config/wiki/Configuration-Files

server:
  port: 3000
  static: true
  live_reload: true

database:
  host: 'localhost'
  port: 2424
  username: 'root'
  password: 'yourpassword'
  dbname: 'genetracker'

# Override this !
secret_token: 'P3RoJCBuof44T2tZm7O9'