# Configuration file : default --
# Based on config : https://github.com/lorenwest/node-config/wiki/Configuration-Files

server:
  port: 3000
  static: true
  live_reload: true

database:
  host: 'localhost'
  port: 2424
  username: 'root'
  password: 'yourpassword'
  dbname: 'genetracker'

# Override this !
secret_token: 'P3RoJCBuof44T2tZm7O9'

# -- Data Schema --
# Don't touch unless you know what you're doing !


data_schema:
  Animal:
    - name: Rat
      path: rats
      property:
        - name: strain
          type: list
          list:
            - id: long_evans
            - id: wistar
            - id: sprague_dawley
          allow_other: true
        - name: date_enter
          type: date
        - name: date_birth
          type: date
        - name: sex
          type: list
          list:
            - id: male
            - id: female
          allow_other: false
        - name: id
          type: text
        - name: age
          type: age
          display_as: week
        - name: origin
          type: list
          list:
            - id: janvier_labs
            - id: charles_river
          allow_other: true
        - name: project
          type: reference
          class: Project
        - name: death
          type: list
          list:
            - id: pentobarbital_end_project
            - id: pentobarbital_tissue_sample
            - id: pentobarbital_suffering
            - id: pre_surgery
            - id: per_surgery
            - id: post_surgery
            - id: beheaded_bio_mol
            - id: found_dead
          allow_other: true
        - name: date_death
          type: date
        - name: date_exit
          type: date
        - name: addressee
          type: text

    - name: Mus
      path: mice
      property:
        - name: strain
          type: text
        - name: lineage
          type: text
        - name: genotype
          type: text
        - name: date_enter
          type: date
        - name: date_birth
          type: date
        - name: sex
          type: list
          list:
            - id: male
            - id: female
          allow_other: false
        - name: id
          type: text
        - name: chip
          type: text
        - name: age
          type: age
          display_as: wee k
        - name: origin
          type: list
          list:
            - id: janvier_labs
            - id: charles_river
            - id: jax_mice
          allow_other: true
        - name: project
          type: reference
          class: Project
        - name: death
          type: list
          list:
            - id: dislocation_end_project
            - id: dislocation_tissue_sample
            - id: dislocation_suffering
            - id: dislocation_unusable
            - id: pentobarbital_end_project
            - id: pentobarbital_tissue_sample
            - id: pentobarbital_suffering
            - id: pre_surgery
            - id: per_surgery
            - id: post_surgery
            - id: beheaded_bio_mol
            - id: found_dead
          allow_other: true
        - name: date_death
          type: date
        - name: date_exit
          type: date
        - name: addressee
          type: text

  User:
    name: User
    path: users
    property:
      - name: username
        type: text
      - name: password
        type: password
      - name: first_name
        type: text
      - name: last_name
        type: text
  Other:
    - name: Project
      path: projects
      property:
      - name: id_apafis
        type: text
      - name: creator
        type: reference
        class: User

